[INCLUDES]
before = common.conf

[Definition]
# Match failed vault login attempts
# Log line example:
#   [2026-01-01 12:00:00.000][vaultwarden::api::identity][ERROR] Username or password is incorrect. Try again. IP: 1.2.3.4. Username: user@example.com.
failregex = ^.*\[vaultwarden::api::identity\]\[ERROR\] Username or password is incorrect\. Try again\. IP: <ADDR>\..*$
            ^.*\[vaultwarden::api::identity\]\[ERROR\] 2FA token invalid.*IP: <ADDR>\..*$

# Match failed admin panel login attempts
            ^.*\[vaultwarden::api::admin\]\[ERROR\] Invalid admin token\. IP: <ADDR>\..*$

ignoreregex =

datepattern = ^\[%%Y-%%m-%%d %%H:%%M:%%S\.\d+\]
